http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
tls:
  stores:
    default:
      defaultCertificate:
        certFile: ./tls-dev.crt
        keyFile: ./tls-dev.key
